SELECT
  PRODUCTLINE AS Category,
  PRODUCTCODE AS SubCategory,
  SUM(SALES) AS Total_Sales,
  SUM(QUANTITYORDERED * PRICEEACH) AS Total_Cost,
  SUM(SALES - (QUANTITYORDERED * PRICEEACH)) AS Profit,
ROUND(SUM(SALES - (QUANTITYORDERED * PRICEEACH)) * 100.0 / SUM(SALES), 2) || '%' AS Profit_Margin_Percentage
FROM sales
GROUP BY PRODUCTLINE, PRODUCTCODE
ORDER BY Profit_Margin_Percentage DESC;
