SELECT PRODUCTCODE, PRODUCTLINE, SUM(QUANTITYORDERED) AS TotalQty, 
       SUM(SALES) AS TotalSales
FROM sales
GROUP BY PRODUCTCODE, PRODUCTLINE
HAVING SUM(QUANTITYORDERED) < 500
   OR SUM(SALES) < 50000
ORDER BY TotalSales ASC;
